- name :  nginx servers
  hosts:  all
  become: yes
  tasks:
    - name: install nginx 
      ansible.builtin.dnf:
          name: nginx
          state: present
    - name: Start service nginx, if not started
      ansible.builtin.service:
        name: nginx
        state: started 
        enabled: yes
  
