
- name: multi playbook
  hosts:  web
  become: yes
  tasks:
    - name: play1 task1
      ansible.builtin.debug:
        msg: "hello play1 task1"

- name: 
  hosts:  web
  become: yes
  tasks:
    - name: play2 task1
      ansible.builtin.debug:
        msg:  "hello play1 task2"