- name: chck given nuber is lower or higher
  hosts: web
  become: yes
  vars:
   number: 2
  tasks:
   - name: print given number is less than 10 or not
     ansible.builtin.debug:
      msg: "given number  {{ number }} is less than 10"
     when: number < 10