- name: install packages by loops
  hosts: web
  become: yes
  tasks:
   - name: install all packages
     ansible.builtin.package:
      msg: "{{ item }}"
     loop:
      - nginx
      - mysql
      - zip