- name: install packages by loops
  hosts: web
  become: yes
  tasks:
   - name: install all packages
     ansible.builtin.package:
      name: "{{ item }}"
      state: latest
     loop:
      - nginx
      - mysql
      - zip